# Generated by Django 3.1.7 on 2021-03-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.AutoField(primary_key=True, serialize=False)),
                ('courier_type', models.IntegerField(choices=[(10, 'foot'), (15, 'bike'), (50, 'car')])),
                ('regions', models.IntegerField()),
                ('working_hours', models.CharField(max_length=11)),
            ],
        ),
    ]
