# Generated by Django 3.1.7 on 2021-03-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours', models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='courier',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='courier',
            name='regions',
            field=models.ManyToManyField(to='cakesapi.Region'),
        ),
        migrations.AddField(
            model_name='courier',
            name='working_hours',
            field=models.ManyToManyField(to='cakesapi.WorkingHours'),
        ),
    ]
