# Generated by Django 3.1.7 on 2021-03-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesapi', '0002_auto_20210320_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_type',
            field=models.IntegerField(choices=[(10, 'Foot'), (15, 'Bike'), (50, 'Car')]),
        ),
    ]
