"""Initial

Revision ID: 9620dd4c037b
Revises: b85258a454ee
Create Date: 2021-03-28 01:47:43.973751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9620dd4c037b'
down_revision = 'b85258a454ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
