"""Initial

Revision ID: b85258a454ee
Revises: 
Create Date: 2021-03-28 01:39:40.499176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85258a454ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('courier_type', sa.Enum('foot', 'bike', 'car', name='courier_type'), nullable=False),
    sa.PrimaryKeyConstraint('courier_id', name=op.f('pk__courier'))
    )
    op.create_table('region',
    sa.Column('region', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('region', name=op.f('pk__region'))
    )
    op.create_table('working_hours',
    sa.Column('working_hours_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('finish_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('working_hours_id', name=op.f('pk__working_hours'))
    )
    op.create_table('courier_region',
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.courier_id'], name=op.f('fk__courier_region__courier_id__courier')),
    sa.ForeignKeyConstraint(['region'], ['region.region'], name=op.f('fk__courier_region__region__region'))
    )
    op.create_table('courier_working_hours',
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('working_hours_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier.courier_id'], name=op.f('fk__courier_working_hours__courier_id__courier')),
    sa.ForeignKeyConstraint(['working_hours_id'], ['working_hours.working_hours_id'], name=op.f('fk__courier_working_hours__working_hours_id__working_hours'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courier_working_hours')
    op.drop_table('courier_region')
    op.drop_table('working_hours')
    op.drop_table('region')
    op.drop_table('courier')
    # ### end Alembic commands ###
